### ISSUE TITLE
transformed elements lose tab-index

### ISSUE THREAD

**Issue by helgatheviking** [jcamenisch/jqTransform#4]
Radio, checkbox and select elements all ignore assigned tab-indices once they've been transformed with the plugin, even though the tax-indices are still in the markup according to firebug

tabbing between text inputs and textareas is fine, but will skip over any radios, checkboxes or selects.

**Comment by jcamenisch** [comment]
These elements don't take focus at all, do they? It might take some hackery to make that work, since the transformation replaces these with divs, spans, and links.

**Comment by helgatheviking** [comment]
nope! i'm not at home, but i was toying around w/ some stuff earlier that worked for dropdowns at least.

**Comment by jcamenisch** [comment]
Awesome. If you can submit a pull request, I'll do my best to find time to accept it.

You might also check others' forks though, to make sure someone hasn't solved this problem already.

**Comment by jcamenisch** [comment]
@helgatheviking, have you checked out DropKick? It looks like it already supports tab index. I'm looking it over and considering switching. https://github.com/JamieLottering/DropKick

The only thing I'm seeing it doesn't have is the ability to sense when it's too close to the bottom of the window, and "drop" upward instead of down. We can add that, though, if it has good bones.

**Comment by helgatheviking** [comment]
no i haven't.  i was able to make a custom drop down, but never had the time to try to make it work with jqTransform.  dropkick looks good though, thanks for the tip.  hope you can merge it into jqtransform.

**Comment by jcamenisch** [comment]
Or maybe abandon jqTransform. :) We shall see. Thanks.
